# Generated by Django 4.0 on 2022-07-08 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Interview_at',
            field=models.DateTimeField(),
        ),
    ]
