# Generated by Django 4.0 on 2022-07-08 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_employee_interview_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Interview_at',
            new_name='BirthDay',
        ),
    ]
