# Generated by Django 4.0 on 2022-07-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_interview_at_employee_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='BirthDay',
            field=models.DateField(),
        ),
    ]
